name: Ping Glitch Server

on:
  workflow_dispatch:       # 👈 Adds the "Run workflow" button
  schedule:
    - cron: '*/5 * * * *'  # Runs every minute (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Glitch /ping
        run: |
          curl -s -A "Mozilla/5.0" https://theplatrix.glitch.me/ping
